### ISSUE TITLE
Bug: PyPortal ADT7410 not working

### ISSUE THREAD

**Issue by morwic** [adafruit/Adafruit_Wippersnapper_Arduino#433] opened 2023-05-26 19:56 UTC
**PyPortal has a built-in ADT7410 component but when I go to add a component IO says,
"Found Addresses:
Used Addresses:
No matching, unused addresses found!
Possible Device Addresses:
0x48 "

***Arduino board***
PyPortal 

**To Reproduce**
1. Go to 'new component '
2. Click on ' ADT7410'
3. See the error

**Expected behavior**
to get temps :)

**Which components are connected to your device**
Built-in ADT7410

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by brentru** [comment] 2023-06-30 17:22
@morwic  I am closing this issue as I'm unable to reproduce it from my end and did not receive a follow-up.

If you are still having trouble, please re-open this issue.

Thanks!

**Closed** 2023-07-03 16:39 UTC
Labels: bug, awaiting feedback
